## YAML Template.
---
driverDB: com.mysql.jdbc.Driver
urlDB: jdbc:mysql://andirexu.heliohost.org:3306/andirexu_navidadesconoscar?useSSL=false
userDB: andirexu_db
passDB: navidadconoscar
mailFrom: alumno1@iesquevedo.es
smtpServer: smtp.gmail.com
smtpPort: 587
mailPass: alumnodam2
minutosParaValidar: 1
longitudCodigo: 50