## YAML Template.
---
driverDB: com.mysql.jdbc.Driver
urlDB: jdbc:mysql://sql11.freemysqlhosting.net:3306/sql11211989?useSSL=false
userDB: sql11211989
passDB: hMriQRzgE2
mailFrom: alumno1@iesquevedo.es
smtpServer: smtp.gmail.com
smtpPort: 587
mailPass: alumnodam2
minutosParaValidar: 1
longitudCodigo: 50