## YAML Template.
---
driverDB: com.mysql.jdbc.Driver
urlDB: jdbc:mysql://37.11.108.51:3307/navidadesconoscar?useSSL=false
userDB: rootchulo
passDB: rootchulo
mailFrom: alumno1@iesquevedo.es
smtpServer: smtp.gmail.com
smtpPort: 587
mailPass: alumnodam2
minutosParaValidar: 1
longitudCodigo: 50